routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|Route::get('/', function () {

    return view('welcome');

});



*/

Route::get('/', 'MainController@home');

Route::get('/carrito', 'ShoppingCartsController@index');

Route::post('/carrito', 'ShoppingCartsController@checkout');

Route::get('/payments/store', 'PaymentsController@store');
Route::get('downloadFile','DownloadController@downloadFile');    
Route::get('getPais/{pais}','Direccions@pais');


Auth::routes();



Route::get('/home', 'HomeController@index');
Route::get('/productslist','MainController@productlist')->name("productlist");





Route::resource('in_shopping_carts', 'InShoppingCartsController', [

    'only' => ['store', 'destroy']

]);

Route::resource('shopping_carts', 'ShoppingCartsController', [

    'only' => ['show', 'destroy']

]);
Route::delete('promotion/{id}','ShoppingCartsController@destroypromo')->name("eliminar_promocion");



Route::get('/Products1', "ProductsController@statics");

//Route::get('/promotions', 'PromotionsController@index');



Route::get('/nosotros', function () {

    return view('static/nosotros');

});

Route::get('/privacidad', function () {

    return view('static/Priv');

});

Route::get('/seguimiento', function () {

    return view('static/seguimiento');

});

Route::get('/servicios', function () {

    return view('static/servicios');
});

Route::get('/faq', function () {

    return view('static/faq');

});

Route::resource('/products', 'ProductsController');




Route::post('/envioshopping','ZonaEnvio\ZonaEnvioController@envios');



Route::get('/creardireccion', 'Direccions@creardireccioninvitado');




Route::post('/user/direccion/create', 'Direccions@store');

Route::get('buscartracking', 'ShoppingCartsController@buscar');




#rutas para form contact

Route::get('contact', 

  ['as' => 'contact', 'uses' => 'AboutController@create']);

Route::post('contact', 

  ['as' => 'contact_store', 'uses' => 'AboutController@store']);

  

Route::get('products/images/{filename}', function ($filename) {

    $path = storage_path("app/images/$filename");
    // dd($path);



    if (!\File::exists($path)) abort(404);



    $file = \File::get($path);



    $type = \File::mimeType($path);



    $response = Response::make($file, 200);



    $response->header("Content-Type", $type);



    return $response;



});



Route::resource('compras', 'ShoppingCartsController', [

    'only' => ['show']

]);
Route::get('pedido/{id}','ShoppingCartsController@pedido');


Route::group(['middleware' => 'auth'], function () {

    
    // Route::group(['middleware' => ['isAdmin']], function () {



    //     Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    //     // Route::get('/admin/sales/excel', 'Admin\SalesController@excel');

    //     Route::resource('/orders', 'OrdersController', [

    //         'only' => ['index', 'update']

    //     ]);

    //     Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');



    //     Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    //     Route::resource('tracking','Tracking\TrackingController');
    //     Route::resource('status','Tracking\StatusTrackingController');

    //     Route::get('/promotions', 'PromotionsController@index');


    //     // Route::get('user', "userprofileController@user");

    //     // Route::get('user/profile', "userprofileController@profile");

    //     // Route::post('user/updateprofile', "userprofileController@updateprofile");

    //     // Route::get('user/password', 'userprofileController@password');

    //     // Route::post('user/updatepassword', 'userprofileController@updatePassword');



    //     // //Route::resource('user/direccion', 'Direccions');

    //     // Route::get('/user/direccion', 'Direccions@index');

    //     // Route::get('/user/direccion/create', 'Direccions@create');

    //     // Route::post('/user/direccion/set_default', 'Direccions@setDefault');



    //     // #rutas para los productos favoritos

    //     // Route::get('/user/my-favorite-products', 'FavoriteProductsController@index');

    //     // Route::get('/user/product/{product_id}/favorite/remove', 'FavoriteProductsController@addremove');

    //     // Route::get('/user/product/{product_id}/favorite/add', 'FavoriteProductsController@addremove');



    //     // #rutas para ver las ordenes de un usuario

    //     // Route::get('/user/my-orders', 'UserOrdersController@index');



    //     // #ruta para obtener la imagen de una receta

    //     // Route::post('/user/order/get-receta', 'UserOrdersController@getReceta');



    //     // #rutas para comentar un producto

    //     // Route::get('/user/product/{product_id}/comment', 'ProductCommentController@getIndex');

    //     // Route::post('/user/product/comment', 'ProductCommentController@storeComment');

    // });

    // Route::group(['middleware' => ['isEmple']], function () {



    //     Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    //     // Route::get('/admin/sales/excel', 'Admin\SalesController@excel');

    //     Route::resource('/orders', 'OrdersController', [

    //         'only' => ['index', 'update']

    //     ]);

    //     Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');
    //     Route::get('/order/info_shopping/{shoppingcart}', 'OrdersController@shoppingInfo');




    //     Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    //     Route::resource('tracking','Tracking\TrackingController');
    //     Route::get('buscartraking','Tracking\TrackingController@search');
    //     Route::resource('status','Tracking\StatusTrackingController');

    //     Route::get('/promotions', 'PromotionsController@index');

    //     Route::post('moneda', 'CambioMonedaController@store');
    //     Route::get('/ordens', 'OrdersController@getOrden');
    //     Route::resource('envios','ZonaEnvio\ZonaEnvioController');

    //     Route::post('generar_orden','OrdersController@generarOrden')->name('generar_orden');
    //     Route::post('reenviar_orden', 'OrdersController@reenviarOrden')->name('reenviar_orden');
    //     Route::get('/marzam_orders', 'OrdersController@pedidos');
    //     Route::post('/marzam_verificado','OrdersController@verificado');
    //     Route::get('/empaquetado','OrdersController@empaquetadoIndex')->name('empaquetado_index');
    //     Route::post('/empaquetar','OrdersController@empaquetarCompra')->name('empaquetado');
    //     Route::get('/tracking/create/{order}', 'OrdersController@createTracking');
    //     Route::get('/order/checkproduct/{shoppingcart}', 'OrdersController@checkingProduct');
    //     Route::post('/producto_check','OrdersController@productoCheck');
    //     Route::post('/promotion_check', 'OrdersController@promotionCheck');
    //     Route::resource('/empleados','Admin\UserController');
    // });


    

    Route::get('user', "userprofileController@user");

    Route::get('user/profile', "userprofileController@profile");

    Route::post('user/updateprofile', "userprofileController@updateprofile");

    Route::get('user/password', 'userprofileController@password');

    Route::post('user/updatepassword', 'userprofileController@updatePassword');



    //Route::resource('user/direccion', 'Direccions');

    Route::get('/user/direccion', 'Direccions@index');

    Route::get('/user/direccion/create', 'Direccions@create');

    Route::post('/user/direccion/set_default', 'Direccions@setDefault');



    #rutas para los productos favoritos

    Route::get('/user/my-favorite-products', 'FavoriteProductsController@index');

    Route::get('/user/product/{product_id}/favorite/remove', 'FavoriteProductsController@addremove');

    Route::get('/user/product/{product_id}/favorite/add', 'FavoriteProductsController@addremove');



    #rutas para ver las ordenes de un usuario

    Route::get('/user/my-orders', 'UserOrdersController@index');



    #ruta para obtener la imagen de una receta

    Route::post('/user/order/get-receta', 'UserOrdersController@getReceta');



    #rutas para comentar un producto

    Route::get('/user/product/{product_id}/comment', 'ProductCommentController@getIndex');

    Route::post('/user/product/comment', 'ProductCommentController@storeComment');
    Route::post('/direccion/delete','Direccions@delete')->name('direccion_delete');

});


/*

 * rutas solamente para usuarios admin check middleware

 */

Route::group(['middleware' => ['isAdmin']], function () {



    Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    Route::resource('envios','ZonaEnvio\ZonaEnvioController');

    Route::post('moneda', 'CambioMonedaController@store');
    
    Route::resource('/empleados','Admin\UserController');
});
Route::group(['middleware' => ['isEmple']], function () {



   
    Route::resource('/orders', 'OrdersController', [

        'only' => ['index', 'update']

    ]);

    Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');
    Route::get('/order/info_shopping/{shoppingcart}', 'OrdersController@shoppingInfo');




    Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    Route::resource('tracking','Tracking\TrackingController');
    Route::get('buscartraking','Tracking\TrackingController@search');
    Route::resource('status','Tracking\StatusTrackingController');

    
    Route::get('/ordens', 'OrdersController@getOrden');

    Route::post('generar_orden','OrdersController@generarOrden')->name('generar_orden');

app/User.php
<?php



namespace App;





use App\Direccion;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;



class User extends Authenticatable {



    use Notifiable, softDeletes;



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = [

        'name', 'email', 'password',

    ];

    protected $dates = ['deleted_at'];



    /**

     * The attributes that should be hidden for arrays.

     *

     * @var array

     */

    protected $hidden = [

        'remember_token', 'created_at', 'updated_at'

    ];



    public function direccions()

    {

        return $this->hasMany('App\Direccion');

    }



    public function favorite_products()

    {

        return $this->belongsToMany('App\Catalogo', 'user_favorite_products', 'user_id', 'catalogo_id');

    }



}


app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{


    public function __construct(){

        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $usuarios = User::where(function($query){
            $query->where('rol','admin')->orWhere('rol','emple');
        })->get();
        return view('admin.user.index',['usuarios'=>$usuarios]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $usuario = new User();
        $edit = false;
        return view('admin.user.create',['usuario'=>$usuario,'edit'=>$edit]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:195',
            'email' => 'required|string|email|max:255|unique:users',
            'rol' => 'required|string',
            'password' => 'required|string|min:6|confirmed',

        ]);
        if ($validator->fails()) {
            # code...
            return redirect()->back()->withErrors($validator)->withInput();
        }
        else{
            $data = $request->all();
            // dd($data);
            $usuario = User::create([
                'name' => $data['name'],
                'email' =>$data['email'],
                
                'password'=>bcrypt($data['password'])
            ]);
            $usuario->rol = $data['rol'];
            $usuario->save();
            return redirect()->route('empleados.index')->with([
                'feedback'=>'Empleado creado correctamente',
                'alert_type' =>'alert-success'

            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($user_id)
    {
        //
        $usuario = User::findOrFail($user_id);
        // dd($usuario);
        $edit=true;
        return view('admin.user.create',['usuario'=>$usuario,'edit'=>$edit]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $empleado)
    {
        //
        // dd($empleado);
        $validator = Validator::make($request->all(),[
            'name' => 'required|max:195',
            'email' => 'required|string|email|max:255',
            'rol' => 'required|string',
        ]);
         if ($validator->fails()) {
            # code...
            return redirect()->back()->withErrors($validator)->withInput();
        }
        else{
            $data = $request->all();
            $empleado->update(['name'=>$data['name'],'email'=>$data['email']]);
            $empleado->rol = $data['rol'];
            $empleado->save();
            return redirect()->route('empleados.index')->with([
                'feedback'=>'Empleado actualizado correctamente',
                'alert_type' =>'alert-success'

            ]);
        }

        // return view('admin.user.create',['usuario'=>$usuario,'edit'=>$edit]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $empleado)
    {
        //
        if ($empleado->rol == 'normal') {
            # code...
            return redirect()->back()->with([
                'feedback'=>'Empleado eliminado',
                'alert_type' =>'alert-success'

            ]);
        }
        else {

            $empleado->delete();
            return redirect()->back()->with([
                    'feedback'=>'Empleado eliminado',
                    'alert_type' =>'alert-success'
                ]);
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')
@section('content')
	{{-- expr --}}
	<section id="four" class="wrapper style1 special fade-up">
		<div id="productos" class="container">
			<div class="panel panel-default dashadmin">
				@include('feedback')
				<div class="panel-heading">
					<h2>{{ $edit == true ? "Editar" : "Nuevo" }} Usuario</h2>
				</div>
				<div class="panel-body">
					            <div class=" panel-default ">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ $edit === true ? route('empleados.update',["empleado"=>$usuario]) : route('empleados.store') }}">
                        {{ csrf_field() }}
                        @if ($edit == true)
                        	{{-- expr --}}
                        	<input type="hidden" name="_method" value="PUT">
                        @endif
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $edit === true ? "$usuario->name" : old('name') }}" required autofocus>
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Correo</label>
                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ $edit === true ? "$usuario->email" : old('email') }}" required>
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('rol') ? ' has-error': '' }}">
                        	<label for="rol" class="col-md-4 control-label">Rol</label>
                        	<div class="col-md-6">
                        		<select class="form-control" id="rol" name="rol">
                        			<option value="admin" {{ $usuario->rol == "admin" ? "selected" : ""}}>Administrador</option>
                        			<option value="emple" {{ $usuario->rol == "emple" ? "selected" : ""}}>Empleado</option>
                        		</select>
                        		@if ($errors->has('rol'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('rol') }}</strong>
                                    </span>
                                @endif
                        	</div>
                        </div>
                        @if ($edit == false)
                        	{{-- expr --}}
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>
                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>
                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>
                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
                        @endif
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary btn-block">
                                    Registrar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')
@section('content')
	{{-- expr --}}
	<section id="four" class="wrapper style1 special fade-up">
		<div id="productos" class="container">
			<div class="panel panel-default dashadmin">
				@include('feedback')
				<div class="panel-heading">
					<h2>Usuarios</h2>
					<a href="{{ route('empleados.create') }}" class="btn btn-info">Nuevo Usuario</a>
				</div>
				<div class="panel-body">
					<table class="table table-bordered tabla-status table-striped">
						<thead>
							<tr>
								<td>Nombre de usuario</td>
								<td>Email</td>
								<td>Rol</td>
								<td>Acciones</td>
							</tr>
						</thead>
						<tbody>
							@foreach ($usuarios as $usuario)
								{{-- expr --}}
								<tr>
									<td>{{$usuario->name}}</td>
									<td>{{$usuario->email}}</td>
									<td>{{$usuario->rol === "admin" ? "Administrador" : "Empleado"}}</td>
									<td>
										<a href="{{ route('empleados.edit',['user_id'=>$usuario->id]) }}" class="btn btn-success">Editar usuario</a>
										<form style="margin: 5px 0 0em 0 !important;" id="destroy {{ $usuario->id }}" method="POST" action="{{ route('empleados.destroy',['empleado'=>$usuario]) }}" onsubmit="return confirm('¿Deseas eliminar a este usuario?');">
											{{ csrf_field() }}
											<input type="hidden" name="_method" value="DELETE">
											<input type="hidden" name="empleado" value="{{$usuario->id}}">
											<button class="btn btn-danger">Eliminar usuario</button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>

@endsection