routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|Route::get('/', function () {

    return view('welcome');

});



*/

Route::get('/', 'MainController@home');

Route::get('/carrito', 'ShoppingCartsController@index');

Route::post('/carrito', 'ShoppingCartsController@checkout');

Route::get('/payments/store', 'PaymentsController@store');
Route::get('downloadFile','DownloadController@downloadFile');    
Route::get('getPais/{pais}','Direccions@pais');


Auth::routes();



Route::get('/home', 'HomeController@index');
Route::get('/productslist','MainController@productlist')->name("productlist");





Route::resource('in_shopping_carts', 'InShoppingCartsController', [

    'only' => ['store', 'destroy']

]);

Route::resource('shopping_carts', 'ShoppingCartsController', [

    'only' => ['show', 'destroy']

]);
Route::delete('promotion/{id}','ShoppingCartsController@destroypromo')->name("eliminar_promocion");



Route::get('/Products1', "ProductsController@statics");

//Route::get('/promotions', 'PromotionsController@index');



Route::get('/nosotros', function () {

    return view('static/nosotros');

});

Route::get('/privacidad', function () {

    return view('static/Priv');

});

Route::get('/seguimiento', function () {

    return view('static/seguimiento');

});

Route::get('/servicios', function () {

    return view('static/servicios');
});

Route::get('/faq', function () {

    return view('static/faq');

});

Route::resource('/products', 'ProductsController');




Route::post('/envioshopping','ZonaEnvio\ZonaEnvioController@envios');



Route::get('/creardireccion', 'Direccions@creardireccioninvitado');




Route::post('/user/direccion/create', 'Direccions@store');

Route::get('buscartracking', 'ShoppingCartsController@buscar');




#rutas para form contact

Route::get('contact', 

  ['as' => 'contact', 'uses' => 'AboutController@create']);

Route::post('contact', 

  ['as' => 'contact_store', 'uses' => 'AboutController@store']);

  

Route::get('products/images/{filename}', function ($filename) {

    $path = storage_path("app/images/$filename");
    // dd($path);



    if (!\File::exists($path)) abort(404);



    $file = \File::get($path);



    $type = \File::mimeType($path);



    $response = Response::make($file, 200);



    $response->header("Content-Type", $type);



    return $response;



});



Route::resource('compras', 'ShoppingCartsController', [

    'only' => ['show']

]);
Route::get('pedido/{id}','ShoppingCartsController@pedido');


Route::group(['middleware' => 'auth'], function () {

    
    // Route::group(['middleware' => ['isAdmin']], function () {



    //     Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    //     // Route::get('/admin/sales/excel', 'Admin\SalesController@excel');

    //     Route::resource('/orders', 'OrdersController', [

    //         'only' => ['index', 'update']

    //     ]);

    //     Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');



    //     Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    //     Route::resource('tracking','Tracking\TrackingController');
    //     Route::resource('status','Tracking\StatusTrackingController');

    //     Route::get('/promotions', 'PromotionsController@index');


    //     // Route::get('user', "userprofileController@user");

    //     // Route::get('user/profile', "userprofileController@profile");

    //     // Route::post('user/updateprofile', "userprofileController@updateprofile");

    //     // Route::get('user/password', 'userprofileController@password');

    //     // Route::post('user/updatepassword', 'userprofileController@updatePassword');



    //     // //Route::resource('user/direccion', 'Direccions');

    //     // Route::get('/user/direccion', 'Direccions@index');

    //     // Route::get('/user/direccion/create', 'Direccions@create');

    //     // Route::post('/user/direccion/set_default', 'Direccions@setDefault');



    //     // #rutas para los productos favoritos

    //     // Route::get('/user/my-favorite-products', 'FavoriteProductsController@index');

    //     // Route::get('/user/product/{product_id}/favorite/remove', 'FavoriteProductsController@addremove');

    //     // Route::get('/user/product/{product_id}/favorite/add', 'FavoriteProductsController@addremove');



    //     // #rutas para ver las ordenes de un usuario

    //     // Route::get('/user/my-orders', 'UserOrdersController@index');



    //     // #ruta para obtener la imagen de una receta

    //     // Route::post('/user/order/get-receta', 'UserOrdersController@getReceta');



    //     // #rutas para comentar un producto

    //     // Route::get('/user/product/{product_id}/comment', 'ProductCommentController@getIndex');

    //     // Route::post('/user/product/comment', 'ProductCommentController@storeComment');

    // });

    // Route::group(['middleware' => ['isEmple']], function () {



    //     Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    //     // Route::get('/admin/sales/excel', 'Admin\SalesController@excel');

    //     Route::resource('/orders', 'OrdersController', [

    //         'only' => ['index', 'update']

    //     ]);

    //     Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');
    //     Route::get('/order/info_shopping/{shoppingcart}', 'OrdersController@shoppingInfo');




    //     Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    //     Route::resource('tracking','Tracking\TrackingController');
    //     Route::get('buscartraking','Tracking\TrackingController@search');
    //     Route::resource('status','Tracking\StatusTrackingController');

    //     Route::get('/promotions', 'PromotionsController@index');

    //     Route::post('moneda', 'CambioMonedaController@store');
    //     Route::get('/ordens', 'OrdersController@getOrden');
    //     Route::resource('envios','ZonaEnvio\ZonaEnvioController');

    //     Route::post('generar_orden','OrdersController@generarOrden')->name('generar_orden');
    //     Route::post('reenviar_orden', 'OrdersController@reenviarOrden')->name('reenviar_orden');
    //     Route::get('/marzam_orders', 'OrdersController@pedidos');
    //     Route::post('/marzam_verificado','OrdersController@verificado');
    //     Route::get('/empaquetado','OrdersController@empaquetadoIndex')->name('empaquetado_index');
    //     Route::post('/empaquetar','OrdersController@empaquetarCompra')->name('empaquetado');
    //     Route::get('/tracking/create/{order}', 'OrdersController@createTracking');
    //     Route::get('/order/checkproduct/{shoppingcart}', 'OrdersController@checkingProduct');
    //     Route::post('/producto_check','OrdersController@productoCheck');
    //     Route::post('/promotion_check', 'OrdersController@promotionCheck');
    //     Route::resource('/empleados','Admin\UserController');
    // });


    

    Route::get('user', "userprofileController@user");

    Route::get('user/profile', "userprofileController@profile");

    Route::post('user/updateprofile', "userprofileController@updateprofile");

    Route::get('user/password', 'userprofileController@password');

    Route::post('user/updatepassword', 'userprofileController@updatePassword');



    //Route::resource('user/direccion', 'Direccions');

    Route::get('/user/direccion', 'Direccions@index');

    Route::get('/user/direccion/create', 'Direccions@create');

    Route::post('/user/direccion/set_default', 'Direccions@setDefault');



    #rutas para los productos favoritos

    Route::get('/user/my-favorite-products', 'FavoriteProductsController@index');

    Route::get('/user/product/{product_id}/favorite/remove', 'FavoriteProductsController@addremove');

    Route::get('/user/product/{product_id}/favorite/add', 'FavoriteProductsController@addremove');



    #rutas para ver las ordenes de un usuario

    Route::get('/user/my-orders', 'UserOrdersController@index');



    #ruta para obtener la imagen de una receta

    Route::post('/user/order/get-receta', 'UserOrdersController@getReceta');



    #rutas para comentar un producto

    Route::get('/user/product/{product_id}/comment', 'ProductCommentController@getIndex');

    Route::post('/user/product/comment', 'ProductCommentController@storeComment');
    Route::post('/direccion/delete','Direccions@delete')->name('direccion_delete');

});


/*

 * rutas solamente para usuarios admin check middleware

 */

Route::group(['middleware' => ['isAdmin']], function () {



    Route::get('/admin/sales', 'Admin\SalesController@getIndex');

    Route::resource('envios','ZonaEnvio\ZonaEnvioController');

    Route::post('moneda', 'CambioMonedaController@store');
    
    Route::resource('/empleados','Admin\UserController');
});
Route::group(['middleware' => ['isEmple']], function () {



   
    Route::resource('/orders', 'OrdersController', [

        'only' => ['index', 'update']

    ]);

    Route::get('/order/info_address/{shoppingcart}', 'OrdersController@getAddressInfo');
    Route::get('/order/info_shopping/{shoppingcart}', 'OrdersController@shoppingInfo');




    Route::get('/admin/recetas', 'Admin\RecetasController@getIndex');

    Route::resource('tracking','Tracking\TrackingController');
    Route::get('buscartraking','Tracking\TrackingController@search');
    Route::resource('status','Tracking\StatusTrackingController');

    
    Route::get('/ordens', 'OrdersController@getOrden');

    Route::post('generar_orden','OrdersController@generarOrden')->name('generar_orden');

app/Order.php
<?php



namespace App;





use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Facades\Mail;

use App\Mail\OrderCreated;



class Order extends Model {



    protected $fillable = [
        'recipient_name', 
        'line1', 
        'line2', 
        'city', 
        'country_code', 
        'state', 
        'postal_code',
        'email', 
        'shopping_cart_id', 
        'status', 
        'total', 
        'guide_numer', 
        'direccion_id', 
        'pedido_file', 
        'verificado',
        'pedido_at',
        'orden_compra_at',
        'empaquetado_at',
        'tracking_at',
        'entregado_at'

    ];



    public function sendMail()

    {

        Mail::to($this->email)->cc($this->shoppingcart->direccion->email)->send(new OrderCreated($this));

    }



    public function shoppingcart()

    {

        return $this->belongsTo('App\ShoppingCart', 'shopping_cart_id');

    }



    // public function scopeLatest($query)

    // {

    //     return $query->orderID()->monthly();

    // }



    public function scopeOrderID($query)

    {

        return $query->orderBy("id", "desc");

    }



    public function scopeMonthly($query)

    {

        return $query->whereMonth("created_at", "=", date('m'));

    }


    public static function total()

    {

        return Order::sum("total");

    }

    public static function totalMonth()

    {

        return Order::monthly()->sum("total");

    }

    public static function totalCount()

    {

        return Order::count();

    }

    public static function totalMonthCount()

    {

        return Order::monthly()->count();

    }





    public function address()

    {

        return "$this->line1 $this->line2";

    }



    public static function createFromPayPalResponse($response, $shopping_cart)

    {

        $payer = $response->payer;



        $orderData = (array) $payer->payer_info->shipping_address;



        $orderData = $orderData[key($orderData)];



        $orderData["email"] = $payer->payer_info->email;

        $orderData["total"] = $shopping_cart->total();

        $orderData["shopping_cart_id"] = $shopping_cart->id;

        $orderData['direccion_id'] = (!is_null($shopping_cart->direccion_id)) ? $shopping_cart->direccion_id : 0;

        return Order::create($orderData);



    }

    public function trackings(){

        return $this->hasMany('App\Tracking','orden_id','id');
    }

   

}


resources/views/orders/addressinfo.blade.php
@if($type_address == 'normal')
    <h4 class="modal-title grey" id="myModalLabel">
        Dirección de Envío:
    </h4>
    <div class="row">
        <div class="col-lg-12">
            <h5 class="modal-title grey" id="myModalLabel">
                <strong>Datos del envio:</strong>
            </h5>
        </div>
        <div class="col-lg-12">
            Nombre: {{ $address->name }}
        </div>
        <div class="col-lg-12">
            Email: {{ $address->email }}
        </div>
        <div class="col-lg-12">
            Telefono: {{ $address->telefono }}
        </div>
        <div class="col-lg-12">
            Telefono 
            contacto: {{ $address->contacto }}
        </div>
        <div class="col-lg-12">
        <h5 class="modal-title grey" id="myModalLabel">
            <strong>Dirección:</strong>
        </h5>
        </div>
        <div class="col-lg-3">
            Calle: {{ $address->calle }}
        </div>
        <div class="col-lg-3">
            Num Ext: {{ $address->num_ext }}
        </div>
        <div class="col-lg-3">
            Num Int: {{ $address->num_int }}
        </div>
        <div class="col-lg-3">
            CP: {{ $address->codigop }}
        </div>
        <div class="col-lg-3">
            Colonia: {{ $address->colonia }}
        </div>
        <div class="col-lg-3">
            País: {{ $address->pais }}        </div>
        <div class="col-lg-3">
            Estado: {{ $address->estado }}
        </div>
        <div class="col-lg-3">
            Ciudad: {{ $address->ciudad }}
        </div>
        <div class="col-lg-3">
            Municipio: {{ $address->municipio }}
        </div>
        <div class="col-lg-3">
        </div>
        <hr/>
        <div class="col-lg-12">
            Entre: {{ $address->entre1 }} Y Entre: {{ $address->entre2 }}
        </div>
        <div class="col-lg-12">
           Referencias: {{ $address->references }}
        </div>
    </div>
@elseif($type_address == 'paypal')
    <div class="row">
        <div class="col-lg-3">
            Calle 1: {{ $address->line1 }}
        </div>
        <div class="col-lg-3">
            Calle 2: {{ $address->line2 }}
        </div>
        <div class="col-lg-3">
            País: {{ $address->country_code }}
        </div>
        <div class="col-lg-3">
            Estado: {{ $address->state }}
        </div>
        <div class="col-lg-3">
            Ciudad: {{ $address->city }}
        </div>
        <div class="col-lg-3">
            CP: {{ $address->postal_code }}
        </div>
    </div>
@endif

resources/views/orders/empaquetado.blade.php
@extends('layouts.app')
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body grey" id="modal-body-address">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@section('content')
	{{-- expr --}}
	<div class="container m-top">
		<div class="panel panel-default dashadmin">
			@include('feedback')
			<div class="panel-heading">
				<h2 class="mt-4">Empaquetado</h2>
				{{-- <form name="buscar" id="buscar" method="GET" action="{{ url('') }}">
				  <div class="input-group center">
				    {{ csrf_field() }}
				    <input type="text" class="form-control" name="orden" placeholder="introduce el custom id" aria-describedby="basic-addon2" autofocus>
				    <a onclick="document.getElementById('buscar').submit()" class="input-group-addon btn btn-success" id="basic-addon2"><i class="fa fa-search"></i></a>
				  </div>
				</form> --}}
			</div>
			<div class="panel-body">
				<table class="table table-bordered tabla-status table-striped">
					<thead>
						<tr>
							<td>Id. de venta</td>
							<td>Comprador</td>
							<td>Información de envio</td>
							<td>Estatus</td>
							<td>fecha de pedido</td>
							<td>Productos</td>
							<td>Acciones</td>
						</tr>
					</thead>
					<tbody>
						@foreach ($ordenes as $orden)
							{{-- expr --}}
							<tr>
								<td>{{$orden->shoppingcart->customid}}</td>
								<td>@if ($orden->shoppingcart->user)
                                {{-- expr --}}
                                {{$orden->shoppingcart->user->name}} | {{$orden->shoppingcart->user->email}}
	                            @else
	                                INVITADO
                            	@endif</td>
                            	<td>
	                                <!-- Button trigger modal -->
	                                <button type="button" class="btn btn-success shopping_cart_address"
	                                        data-shoppingcart="{{ $orden->shopping_cart_id }}">
	                                    <i class="fa fa-eye"></i>Dirección
	                                </button>
	                            </td>
	                            <td>{{$orden->status}}</td>
	                            <td>{{$orden->updated_at}}</td>
	                            <td>
									<button type="button" class="btn btn-info infoshopping" data-shoppingcart="{{ $orden->shopping_cart_id }}">
									<i class="fa fa-eye"></i>Productos
									</button>
                                </td>
                                <td>
									<form action="{{ url('/empaquetar') }}" method="POST" id="form-verificar-orden {{ $orden->id }}" style="margin: 0px 0 1em 0;">
									{{ csrf_field() }}
	                                    <div class="checkbox">
	                                    	<label><input type="checkbox" value="{{$orden->id}}" {{$orden->empaquetado_at ? 'checked disabled' : ''}} name="verificar" id="verificar" onChange="if(confirm('desea confirmar el pedido a marzam')){this.form.submit();}else{this.checked = false}">Empaquetado</label>
	                                    </div>
	                                    {{-- <input type="radio" name="url_receta_path"
	                                           value="{{ $orden->shoppingcart->receta_path }}"/>
	                                           <label>empaquetado_at</label> --}}
	                                    {{-- <button class="btn btn-sm btn-info">empaquetado</button> --}}
	                                </form>
	                                <button type="button" {{$orden->empaquetado_at ? '' : 'disabled'}} class="btn btn-sm btn-secondary tracking_add"
										data-ordentrack="{{ $orden->id }}">
	                                    Agregar número de tracking
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection
@section('scripts')
	{{-- expr --}}
	<script>
		function verificar(etiqueta){
			if(confirm("¿Desea confirmar el empaquetado?")){
				document.getElementById("form-verificar-orden "+etiqueta).submit();
			}
		}
		$(function () {
            $(".shopping_cart_address").on('click', function (e) {
                e.preventDefault();
                var shoppingcart = $(this).data('shoppingcart');
                // acemos la peticion ajax para obtener la plantilla del carrito
                $.ajax({
					url: '{{ url('/order/info_address/') }}/' + shoppingcart,					
					type: 'GET',					
                    success: function (data) {
						$("#modal-body-address").html(data);
						$("#myModal").modal('show');
					}
				})
			});
		});		
        $(function (){
            $(".infoshopping").on('click', function(e){
                e.preventDefault();
				var shoppingcart = $(this).data('shoppingcart');				
                $.ajax({
                    url: '{{ url('/order/checkproduct') }}/'+shoppingcart,
					type: 'GET',					
                    success: function(data){
                        $('#modal-body-address').html(data);
                        $('#myModal').modal('show');
                    }
                });
            });
		});
		
        $(function (){
            $(".tracking_add").on('click', function(e){
                e.preventDefault();
                var shoppingcart = $(this).data('ordentrack');
                // console.log(shoppingcart);
                $.ajax({
                    url: '{{ url('/tracking/create/') }}/'+shoppingcart,
                    type: 'GET',
                    success: function(data){
                        $('#modal-body-address').html(data);
                        $('#myModal').modal('show');
                    }
                });
            });
        });        
	</script>
@endsection

resources/views/orders/marzam.blade.php
@extends('layouts.app')
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body grey" id="modal-body-address">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@section('content')
	{{-- expr --}}
	<div class="container m-top">
		<div class="panel panel-default dashadmin">
			 @include('feedback')
			<div class="panel-heading">
				<h2>Pedidos a Marzam</h2>
				{{-- <form name="buscar_tracking" id="buscar_tracking" method="GET" action="{{ url('/buscartracking') }}">
				  <div class="input-group center">
				    {{ csrf_field() }}
				    <input type="text" class="form-control" name="tracking" placeholder="introduce el custom id" aria-describedby="basic-addon2" autofocus>
				    <a onclick="document.getElementById('buscar_tracking').submit()" class="input-group-addon btn btn-success" id="basic-addon2"><i class="fa fa-search"></i></a>
				  </div>
				</form> --}}
			</div>
			<div class="panel-body">
				<table class="table table-bordered tabla-status table-striped">
					<thead>
						<tr>
							<td>Id de venta</td>
							<td>Comprador</td>
							<td>Destinatario</td>
							<td>Dirección</td>
							<td>Estatus</td>
							<td>Fecha de Venta</td>
							<td>Carrito de compra</td>
							<td>Acciones</td>
						</tr>
					</thead>
					<tbody>
						@foreach ($ordenes as $orden)
							{{-- expr --}}
							<tr>
								<td>{{$orden->shoppingcart->customid}}</td>
								<td>@if ($orden->shoppingcart->user)
                                {{-- expr --}}
                                {{$orden->shoppingcart->user->name}} | {{$orden->shoppingcart->user->email}}
	                            @else
	                                INVITADO
                            	@endif</td>
                            	<td>{{ $orden->recipient_name }}</td>
                            	<td>
	                                <!-- Button trigger modal -->
	                                <button type="button" class="btn btn-success shopping_cart_address"
	                                        data-shoppingcart="{{ $orden->shopping_cart_id }}">
	                                    <i class="fa fa-eye"></i>Dirección
	                                </button>
	                            </td>
	                            <td>{{$orden->status}}</td>
	                            <td>{{ $orden->created_at }}</td>
	                            <td><button type="button" class="btn btn-info infoshopping" data-shoppingcart="{{ $orden->shopping_cart_id }}">
                                    <i class="fa fa-eye"></i>Productos
                                </button>
                                </td>
                                <td>
                                	<form action="{{ url('/marzam_verificado') }}" method="POST" id="form-verificar-orden {{ $orden->id }}" style="margin: 0px 0 1em 0;">
	                                    {{ csrf_field() }}
	                                    <div class="checkbox">
	                                    	<label><input type="checkbox" value="{{$orden->id}}" {{$orden->verificado ? 'checked disabled' : ''}} name="verificar" id="verificar" onChange="if(confirm('desea confirmar el pedido a marzam')){this.form.submit();}else{this.checked = false}">Verificado</label>
	                                    </div>
	                                    {{-- <input type="radio" name="url_receta_path"
	                                           value="{{ $orden->shoppingcart->receta_path }}"/>
	                                           <label>verificado</label> --}}
	                                    {{-- <button class="btn btn-sm btn-info">Verificado</button> --}}
	                                </form>
	                                <form {{$orden->verificado ? 'disabled' : ''}} id="orden {{ $orden->id }}" action="{{ route('reenviar_orden') }}" method="POST" style="margin: 0px 0 1em 0;">
	                                    {{ csrf_field() }}
	                                    <input type="hidden" name="orden"
	                                           value="{{ $orden->id }}"/>
	                                    <a type="submit" {{$orden->verificado ? 'disabled' : ''}} @if ($orden->verificado == 0)
	                                    	{{-- expr --}}
	                                    	onclick="deleteFunction('orden {{ $orden->id }}')"
	                                    @endif  class="btn btn-sm btn-secondary text-white">Reenviar Orden
	                                     de <br> Compra</a>
	                                </form>
                                </td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
	{{-- expr --}}
	<script>
		function deleteFunction(etiqueta) {
            event.preventDefault(); // prevent form submit
            if (confirm("¿Deseas reenviar tu pedido a marzam?")){
                document.getElementById(etiqueta).submit();          // submitting the form when user press yes
            }
        }
		function verificar(etiqueta){
			if(confirm("¿Desea confirmar la verificación de este pedido a marzam?")){
				document.getElementById("form-verificar-orden "+etiqueta).submit();
			}

		}
		
		$(function () {

            $(".shopping_cart_address").on('click', function (e) {

                e.preventDefault();

                var shoppingcart = $(this).data('shoppingcart');
                // acemos la peticion ajax para obtener la plantilla del carrito
                $.ajax({
                    url: '{{ url('/order/info_address/') }}/' + shoppingcart,
                    type: 'GET',
                    success: function (data) {
                        $("#modal-body-address").html(data);
                        $("#myModal").modal('show');
                    }
                })
            });
        });
        $(function (){
            $(".infoshopping").on('click', function(e){
                e.preventDefault();
                var shoppingcart = $(this).data('shoppingcart');
                $.ajax({
                    url: '{{ url('/order/info_shopping') }}/'+shoppingcart,
                    type: 'GET',
                    success: function(data){
                        $('#modal-body-address').html(data);
                        $('#myModal').modal('show');
                    }
                });
            });
        });
	</script>
@endsection

resources/views/orders/tracking.blade.php
	<h4 class="modal-title grey" id="myModalLabel">
		Nuevo Tracking:
	</h4>
	<div class="col-lg-12">
		<form method="POST" action="{{ route('tracking.store') }}">
			{{ csrf_field() }}
			<div class="modal-body">
				<div class="row">
					<div class="col-sm-6">
						<label for="hawb">HAWB:</label>
						<input type="text" class="form-control" name="hawb" id="hawb" placeholder="Clave HAWB" required>
					</div>
					<div class="col-sm-6">
						<label for="orden_id">Orden de Compra:</label>
						<select class="form-control" id="orden_id" name="orden_id" required readonly>
							<option value="{{$orden->id}}" selected>{{$shopping_cart->customid}}</option>
						</select>
					</div>
					<div class="col-sm-offset-1 col-sm-10">
						<label for="destino">Destino:</label>
						<input class="form-control" type="text" name="destino" id="destino" placeholder="Destino" required value="{{ $direccion->municipio }}, {{$direccion->estado}}, {{$direccion->pais}}">
					</div>
					<div class="col-sm-6">
						<label for="bultos">Número de Bultos</label>
						<select class="form-control" id="bultos" name="bultos" required>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
						</select>
					</div>
					<div class="col-sm-6">
						<label for="peso">Peso:</label>
						<input class="form-control" type="number" name="peso" id="peso" step="0.50" min="0.50" max="30" placeholder="-Kg-" required>
					</div>
					<div class="col-sm-offset-1 col-sm-10">
						<textarea class="form-control" readonly="readonly" id="direccion" rows="8">Calle {{ $direccion->calle }}, #{{$direccion->num_ext}} {{$direccion->num_int ? "Int $direccion->num_int," : ","}} Colonia {{$direccion->colonia}}, Municipio {{$direccion->municipio}}, Estado {{$direccion->estado}}, Ciudad {{$direccion->ciudad}}, País {{$direccion->pais}} </textarea>
					</div>
				</div>
			</div>
			<input type="submit" class="btn btn-success pull-right" value="Guardar">
		</form>
	</div>